In [ ]:
import numoy as np


In [38]:
np.__version__

'2.2.2'

In [39]:
import sys
sys.version

'3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]'

In [40]:
my_lis=[1,2,3,4,5]
my_lis

[1, 2, 3, 4, 5]

In [41]:
type(my_lis)

list

convert list to array

In [42]:
arr=np.array(my_lis)

In [43]:
type(arr)

numpy.ndarray

In [44]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
np.arange(3.0)

array([0., 1., 2.])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [48]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.arange(20,10)

array([], dtype=int64)

In [50]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [51]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [52]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [53]:
np.arange(30,20)

array([], dtype=int64)

In [54]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [55]:
np.arange(10,10)

array([], dtype=int64)

In [56]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [57]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [58]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [60]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [63]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [64]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [65]:
lst=np.array([[1,2,3],[4,5,6]])

In [66]:
lst

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
lst.dtype

dtype('int64')

In [68]:
lst.shape

(2, 3)

In [69]:
lst.size

6

In [70]:
np.ones((3),dtype=int)

array([1, 1, 1])

In [35]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [57]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
rand(3,2)

In [ ]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
np.random.rand(5)

array([0.62398129, 0.85920542, 0.70612162, 0.86357261, 0.30628006])

In [61]:
np.random.rand(10)

array([0.25398261, 0.97180047, 0.28392081, 0.78855905, 0.05071519,
       0.75466629, 0.24422272, 0.91413323, 0.46025672, 0.25614348])

In [60]:
np.random.randint(2,4)

3

In [6]:
np.random.randint(5)

0

In [7]:
np.random.rand(7)

array([0.20474053, 0.66025669, 0.26543682, 0.05953601, 0.81645567,
       0.82078874, 0.73647067])

In [8]:
np.random.random(1)

array([0.84962246])

In [26]:
np.random.rand((90))

array([1.66164063e-01, 8.73288458e-02, 7.38615320e-01, 4.87004867e-01,
       8.86226514e-01, 3.14967077e-01, 8.41516690e-01, 5.89067714e-01,
       4.09008517e-01, 1.36965311e-01, 2.56306774e-01, 8.76355761e-01,
       7.02656945e-01, 5.33563110e-01, 1.68302875e-01, 3.41165976e-01,
       9.62548959e-01, 5.83296202e-01, 4.99687741e-01, 6.44953649e-01,
       1.16788075e-01, 8.07282170e-01, 4.96333243e-01, 7.19054936e-01,
       5.75920093e-01, 7.77210079e-01, 1.65973159e-01, 3.68429394e-01,
       7.06341443e-01, 3.38968508e-01, 1.22843237e-01, 4.25523157e-01,
       6.66760018e-01, 5.69169682e-01, 6.56239416e-01, 7.05415292e-01,
       4.50480074e-02, 3.99300858e-01, 9.97807188e-01, 6.90960259e-01,
       6.33467023e-01, 4.01627053e-01, 6.97058588e-02, 7.22184764e-01,
       2.31766170e-01, 1.03693092e-01, 3.55906067e-01, 2.59765509e-01,
       7.70320879e-01, 3.96453423e-01, 4.71206724e-01, 5.67428339e-01,
       5.98445143e-01, 4.49069139e-01, 8.47807120e-02, 7.95673159e-01,
      

In [14]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [15]:
type(my_list)

list

In [16]:
x=np.array((my_list))

In [17]:
x

array([1, 2, 3, 4])

In [19]:
x.dtype

dtype('int64')

In [20]:
x.size

4

In [21]:
x.shape

(4,)

In [22]:
np.ones((7))

array([1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((10),int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.ones((2),int)

array([1, 1])

In [29]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
np.random.rand((7))

array([0.63633287, 0.97582282, 0.79563839, 0.562732  , 0.72849074,
       0.8780952 , 0.364034  ])

In [34]:
np.random(3)

TypeError: 'module' object is not callable

In [36]:
np.random.randint((3))

1

In [37]:
np.random.rand((10))

array([0.45927298, 0.87316777, 0.19428958, 0.69436993, 0.10033537,
       0.78266777, 0.09590903, 0.66533345, 0.54456851, 0.48889803])

In [38]:
np.random.rand(5)

array([0.92837592, 0.51381017, 0.3857057 , 0.0452399 , 0.84799468])

In [44]:
np.random.randint((3))

0

range

In [45]:
range(2)

range(0, 2)

In [48]:
a=list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
s=list(range(1,78))
s

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77]

In [51]:
d=list(range(1,50,5))
d

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46]

In [54]:
f=list(range(7,77,7))
f

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70]

In [56]:
t=range(50)
for i in t:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [57]:
np.arange((2))

array([0, 1])

In [60]:
np.arange((7))

array([0, 1, 2, 3, 4, 5, 6])

In [61]:
np.arange((101))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [62]:
np.arange(7,77,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [64]:
np.arange(5,50)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [65]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [66]:
np.arange(80)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [67]:
np.arange(90)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [72]:
np.zeros((3,9),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [74]:
np.ones((4),int)

array([1, 1, 1, 1])

In [76]:
np.random.rand((2))

array([0.12299733, 0.84096717])

In [77]:
np.random.randint(8)

5

In [90]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [91]:
np.ones(3)

array([1., 1., 1.])

In [93]:
np.random.randint(20,30,10)

array([23, 28, 28, 21, 22, 29, 21, 27, 28, 29], dtype=int32)

In [94]:
np.random.randint(5,9)

7

In [101]:
np.random.randint(10,40,(10,10))

array([[11, 37, 36, 22, 20, 17, 37, 38, 13, 21],
       [16, 27, 14, 17, 35, 29, 30, 23, 28, 34],
       [24, 31, 27, 30, 15, 24, 32, 25, 15, 16],
       [24, 11, 38, 19, 26, 19, 11, 13, 22, 26],
       [17, 36, 32, 18, 21, 37, 11, 11, 32, 15],
       [31, 13, 11, 24, 37, 28, 11, 16, 22, 13],
       [13, 18, 32, 31, 35, 27, 16, 26, 17, 18],
       [28, 12, 38, 28, 37, 32, 13, 34, 28, 17],
       [23, 34, 20, 29, 38, 24, 21, 28, 16, 11],
       [39, 33, 19, 10, 19, 15, 35, 37, 34, 34]], dtype=int32)

In [108]:
np.random.randint(10,100,(12,12))

array([[44, 71, 18, 55, 79, 71, 97, 94, 26, 11, 51, 27],
       [61, 40, 94, 68, 10, 73, 74, 50, 52, 17, 86, 44],
       [41, 61, 13, 22, 75, 29, 43, 62, 12, 91, 72, 17],
       [52, 23, 93, 46, 19, 37, 41, 66, 99, 61, 44, 20],
       [49, 93, 85, 27, 28, 11, 51, 13, 42, 29, 84, 30],
       [52, 24, 16, 75, 11, 12, 74, 36, 41, 37, 79, 40],
       [68, 25, 60, 22, 81, 67, 77, 40, 54, 24, 48, 46],
       [83, 11, 25, 34, 32, 47, 58, 81, 46, 11, 92, 97],
       [49, 12, 87, 99, 66, 78, 69, 41, 88, 52, 34, 41],
       [73, 84, 82, 65, 84, 16, 18, 45, 59, 64, 27, 62],
       [35, 60, 24, 83, 22, 54, 50, 97, 26, 12, 78, 85],
       [61, 36, 10, 65, 31, 14, 39, 66, 40, 72, 66, 42]], dtype=int32)

In [109]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
a77=np.arange(1,16).reshape(3,5)

In [75]:
a77

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [76]:
a77[2,4]

np.int64(15)

In [80]:
w=a77.T

In [81]:
w

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [83]:
w[4,2]

np.int64(15)

In [110]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [112]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [85]:
a=np.random.randint(10,20,(5,4))

In [86]:
type(a)

numpy.ndarray

In [87]:
a

array([[18, 13, 13, 10],
       [12, 17, 17, 16],
       [12, 10, 10, 14],
       [11, 19, 17, 10],
       [16, 18, 16, 14]], dtype=int32)

In [92]:
type(a)

numpy.ndarray

In [97]:
# it print single column
a[:,2]

array([13, 17, 10, 17, 16], dtype=int32)

In [99]:
a[:,1]

array([13, 17, 10, 19, 18], dtype=int32)

: 

In [98]:
a[1]

array([12, 17, 17, 16], dtype=int32)

In [ ]:
mat=np.arange

In [78]:
o=[12,34,56,78,90]
o

[12, 34, 56, 78, 90]

In [80]:
type(o)

list

In [86]:
p=np.array(o)

In [87]:
p.dtype

dtype('int64')

In [88]:
p.size

5

In [89]:
p.shape

(5,)