numpy

In [1]:
import numpy as np

 

ModuleNotFoundError: No module named 'numpy'

In [2]:
x=np.array([[2,3,3,4,5,6,6]],np.int32)

In [3]:
print(x,type(x),len(x))

[[2 3 3 4 5 6 6]] <class 'numpy.ndarray'> 1


In [4]:
x.dtype

dtype('int32')

In [5]:
x.shape

(1, 7)

In [6]:
d=np.array([[1,4,6,5] ,[2,6,8,3] ,[9,5,3,4]])

In [7]:
d

array([[1, 4, 6, 5],
       [2, 6, 8, 3],
       [9, 5, 3, 4]])

In [8]:
d.dtype

dtype('int64')

In [9]:
d.size

12

In [10]:
d.shape

(3, 4)

In [11]:
a=np.array({2,4,5,7})

In [12]:
a.dtype

dtype('O')

In [13]:
a.size

1

In [14]:
a.shape

()

In [15]:
z= np.zeros((7,7))

In [16]:
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
z.dtype

dtype('float64')

In [18]:
z.size

49

In [19]:
z.shape

(7, 7)

In [20]:
rang=np.arange((99))

In [21]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
rang.dtype

dtype('int64')

In [23]:
rang.size

99

In [24]:
rang.shape

(99,)

In [25]:
l1=np.linspace(12,5,7)

In [26]:
l1

array([12.        , 10.83333333,  9.66666667,  8.5       ,  7.33333333,
        6.16666667,  5.        ])

In [27]:
l=np.linspace(0,50,3)

In [28]:
l

array([ 0., 25., 50.])

In [29]:
e=np.empty((4,6))

In [30]:
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60216183e-306, 7.56602523e-307,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23037657e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 1.60220800e-306,
        7.56589622e-307, 1.11260144e-306, 8.34449806e-308]])

In [31]:
empike=np.empty_like(l1)

In [32]:
empike

array([12.        , 10.83333333,  9.66666667,  8.5       ,  7.33333333,
        6.16666667,  5.        ])

In [33]:
mp=np.identity(45)

In [34]:
mp

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [35]:
np.shape(mp)

(45, 45)

In [36]:
mp

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [37]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
rang.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
rang=rang.ravel()

In [41]:
rang.shape

(99,)

In [42]:
m=([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
m=np.array(m)

In [44]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

in numpy also axis starts from 0 

In [45]:
m.sum(axis=0)

array([12, 15, 18])

In [46]:
m.sum(axis=1)

array([ 6, 15, 24])

In [47]:
l1

array([12.        , 10.83333333,  9.66666667,  8.5       ,  7.33333333,
        6.16666667,  5.        ])

in this form of fuctions we add the new array in form second array


In [48]:
g=np.empty_like((l1),dtype=int)

In [49]:
g

array([4622945017495814144, 4622288242550155947, 4621631467604497749,
       4620974692658839552, 4619942617744233813, 4618629067852917418,
       4617315517961601024])

in this linspace we got the value of gapping 

In [50]:
s=np.linspace(10,100,10)
s

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [51]:
d=np.linspace(10,200,10)
d

array([ 10.        ,  31.11111111,  52.22222222,  73.33333333,
        94.44444444, 115.55555556, 136.66666667, 157.77777778,
       178.88888889, 200.        ])

In [52]:
r=np.identity((7),dtype=int)
r

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [53]:
r.dtype

dtype('int64')

In [54]:
r.shape

(7, 7)

In [55]:
r.size

49

we want x*x matrix in this form

In [56]:
t=np.identity(100)
t

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(100, 100))

In [57]:
t.dtype

dtype('float64')

In [58]:
t.shape

(100, 100)

In [59]:
t.size

10000

In [60]:
p=np.arange(99)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

reshape the array as we choise

In [61]:
u=p.reshape(3,33)

In [62]:
u

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

code in 1d

In [63]:
up=u.ravel()

In [64]:
up

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# creating a new array

In [65]:
A=np.array([[12,33,45,67],[1,2,3,4],[13,14,15,26],[19,76,54,33]])

In [66]:
print(A)
print(A.dtype)
print(A.size)
print(A.shape)

[[12 33 45 67]
 [ 1  2  3  4]
 [13 14 15 26]
 [19 76 54 33]]
int64
16
(4, 4)


In [67]:
A.sum(axis=0)

array([ 45, 125, 117, 130])

In [68]:
A.sum(axis=1)

array([157,  10,  68, 182])

In [69]:
q=np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44]])

In [70]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [71]:
q.dtype

dtype('int64')

In [72]:
q.size

12

In [73]:
q.shape

(3, 4)

In [74]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [75]:
q.T

array([[ 1,  5, 11],
       [ 2,  6, 22],
       [ 3,  7, 33],
       [ 4,  8, 44]])

for loop

In [76]:
for item in q.flat:
    print(item)

1
2
3
4
5
6
7
8
11
22
33
44


In [77]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [78]:
print(q.sum(axis=0))
print(q.sum(axis=1))

[17 30 43 56]
[ 10  26 110]


In [79]:
q.ndim

2

In [80]:
q.nbytes

96

In [81]:
t=np.array([21,22,23,344,5848,3,245553,223])

In [82]:
t

array([    21,     22,     23,    344,   5848,      3, 245553,    223])

In [83]:
t.argmax()

np.int64(6)

In [84]:
t.argmin()

np.int64(5)

In [85]:
t.argsort()

array([5, 0, 1, 2, 7, 3, 4, 6])

In [86]:
t.sort()
t

array([     3,     21,     22,     23,    223,    344,   5848, 245553])

In [87]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [88]:
q.sort()
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [89]:
q.T

array([[ 1,  5, 11],
       [ 2,  6, 22],
       [ 3,  7, 33],
       [ 4,  8, 44]])

In [90]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [91]:
q.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [92]:
q.argmax()

np.int64(11)

In [93]:
q.argmin()

np.int64(0)

In [94]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [95]:
q.argmin(axis=0)

array([0, 0, 0, 0])

In [96]:
q.argmin(axis=1)

array([0, 0, 0])

In [97]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [98]:
q.sort()
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [99]:
q.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [100]:
q.argsort(axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [101]:
q.argsort(axis=1)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [102]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [103]:
q[1,3]

np.int64(8)

In [104]:
q[2,3]

np.int64(44)

In [105]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [106]:
q.min()

np.int64(1)

In [107]:
q.max()

np.int64(44)

In [108]:
q.sum()

np.int64(146)

In [109]:
q.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 22, 33, 44])

In [110]:
q1=np.array([[9,8,7,6],[6,5,4,3],[3,2,1,0]])

In [111]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [112]:
q1

array([[9, 8, 7, 6],
       [6, 5, 4, 3],
       [3, 2, 1, 0]])

In [113]:
q+q1

array([[10, 10, 10, 10],
       [11, 11, 11, 11],
       [14, 24, 34, 44]])

In [114]:
q*q1

array([[ 9, 16, 21, 24],
       [30, 30, 28, 24],
       [33, 44, 33,  0]])

In [115]:
q-q1

array([[-8, -6, -4, -2],
       [-1,  1,  3,  5],
       [ 8, 20, 32, 44]])

In [116]:
q1/q

array([[9.        , 4.        , 2.33333333, 1.5       ],
       [1.2       , 0.83333333, 0.57142857, 0.375     ],
       [0.27272727, 0.09090909, 0.03030303, 0.        ]])

In [117]:
np.sqrt(q)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.31662479, 4.69041576, 5.74456265, 6.63324958]])

In [118]:
np.sqrt(q1)

array([[3.        , 2.82842712, 2.64575131, 2.44948974],
       [2.44948974, 2.23606798, 2.        , 1.73205081],
       [1.73205081, 1.41421356, 1.        , 0.        ]])

In [119]:
q1.sum()

np.int64(54)

In [120]:
q1.min()

np.int64(0)

In [121]:
q1.max()

np.int64(9)

In [122]:
q1

array([[9, 8, 7, 6],
       [6, 5, 4, 3],
       [3, 2, 1, 0]])

In [123]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [124]:
np.where(q>5)

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [125]:
np.where(q1>7)

(array([0, 0]), array([0, 1]))

In [126]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [127]:
np.count_nonzero(q)

12

In [128]:
np.nonzero(q)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [129]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [130]:
q[0,3]=7

In [131]:
q

array([[ 1,  2,  3,  7],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [132]:
q[1,3]=8

In [133]:
q

array([[ 1,  2,  3,  7],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [134]:
import sys

In [135]:
check=[1,12,23,45]

In [136]:
check1=np.array([[1,12,23,45]])

In [137]:
check.__sizeof__()*len(check)

288

In [138]:
check1.itemsize*check1.size

32

In [141]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [143]:
# masking
a[a<8]

array([0, 1, 2, 3, 4, 5, 6, 7])

: 